stages:
  - build
  - benchmark
  - benchmark-completion

variables:
  PYTHONUNBUFFERED: "true"
  GRAALVM_ARCHIVE: /home/gitlab-runner/.local/graalvm-0.12-linux-x86_64-dk.tar.gz
  RUBINIUS_BIN: /home/gitlab-runner/.local/rubinius/3.14/bin/rbx

.benchmark-settings:
  executors: &EXECUTORS |
    export EXECUTORS=(
      e:Java8-int
      e:Java17-int
      e:Java8-C2-jit
      e:Java17-C2-jit
      e:Java-GraalCE-jit
      e:Java-GraalEE-jit
      # e:Java-NativeCE
      # e:Java-NativeEE
  
      e:SOM-Java17-C2
      # "e:SOMpp"
      # "e:SOMppOMR"
      e:TruffleSOM-ast-CE-jit
      e:TruffleSOM-bc-CE-jit
      e:TruffleSOM-ast-NativeCE-int
      e:TruffleSOM-bc-NativeCE-int
      
      # "e:TruffleSOM-Enterprise"
      # "e:TruffleSOM-TOM"
      # "e:TruffleSOM-TOM-Enterprise"
  
      e:PySOM-ast-jit
      e:PySOM-ast-int
      e:PySOM-bc-jit
      e:PySOM-bc-int

      # "e:SOMns"
      # "e:SOMnsInt"
      # "e:SOMns-Enterprise"
  
      e:TruffleRuby-CE-jit
      e:TruffleRuby-EE-jit
      e:TruffleRuby-NativeCE-int
      # e:TruffleRuby-NativeEE-int
      e:TruffleRuby-NativeCE-jit
      # e:TruffleRuby-NativeEE-jit
  
      # "e:JRubyTruffleEnterprise"
      # "e:JRubyC2"
      # "e:JRubyJ8"
      # "e:JRubyGraal"

      e:CRuby27-int
      e:CRuby30-int
      
      # "e:Crystal"

      e:Node-jit
      e:Node-int

      # "e:GraalJS"
  
      # "e:Pharo"
      # "e:Squeak"
      # "e:RSqueak"

      # e:LuaJIT2
      # e:Lua53
  
      # e:Cinder-jit
      # e:PyPy-jit
      # e:CPython-interp
  
      # e:Pyston-jit
      # e:GraalPython-jit
    )
  params-build: &PARAMS_BUILD export PARAMS="-f --setup-only --disable-data-reporting"
  params-run:   &PARAMS_RUN   export PARAMS="-f --without-building"
    

before_script:
  - git submodule update --init --recursive

build-y1:
  stage: build
  tags: [yuria]
  script:
    - *EXECUTORS
    - *PARAMS_BUILD
    - rebench $PARAMS codespeed.conf all "${EXECUTORS[@]}"

build-y2:
  stage: build
  tags: [yuria2]
  script:
    - *EXECUTORS
    - *PARAMS_BUILD
    - rebench $PARAMS codespeed.conf all "${EXECUTORS[@]}"

build-y3:
  stage: build
  tags: [yuria3]
  script:
    - *EXECUTORS
    - *PARAMS_BUILD
    - rebench $PARAMS codespeed.conf all "${EXECUTORS[@]}"


deltablue:
  stage: benchmark
  tags: [yuria]
  script:
    - *EXECUTORS
    - *PARAMS_RUN
    - rebench $PARAMS --experiment="CI ID $CI_PIPELINE_ID" --branch="$CI_COMMIT_REF_NAME" codespeed.conf all "${EXECUTORS[@]}" s:*:DeltaBlue

richards:
  stage: benchmark
  tags: [yuria2]
  script:
    - *EXECUTORS
    - *PARAMS_RUN
    - rebench $PARAMS --experiment="CI ID $CI_PIPELINE_ID" --branch="$CI_COMMIT_REF_NAME" codespeed.conf all "${EXECUTORS[@]}" s:*:Richards

json:
  stage: benchmark
  tags: [yuria3]
  script:
    - *EXECUTORS
    - *PARAMS_RUN
    - rebench $PARAMS --experiment="CI ID $CI_PIPELINE_ID" --branch="$CI_COMMIT_REF_NAME" codespeed.conf all "${EXECUTORS[@]}" s:*:Json

cd:
  stage: benchmark
  tags: [yuria]
  script:
    - *EXECUTORS
    - *PARAMS_RUN
    - rebench $PARAMS --experiment="CI ID $CI_PIPELINE_ID" --branch="$CI_COMMIT_REF_NAME" codespeed.conf all "${EXECUTORS[@]}" s:*:CD

havlak:
  stage: benchmark
  tags: [yuria2]
  script:
    - *EXECUTORS
    - *PARAMS_RUN
    - rebench $PARAMS --experiment="CI ID $CI_PIPELINE_ID" --branch="$CI_COMMIT_REF_NAME" codespeed.conf all "${EXECUTORS[@]}" s:*:Havlak

bounce:
  stage: benchmark
  tags: [yuria3]
  script:
    - *EXECUTORS
    - *PARAMS_RUN
    - rebench $PARAMS --experiment="CI ID $CI_PIPELINE_ID" --branch="$CI_COMMIT_REF_NAME" codespeed.conf all "${EXECUTORS[@]}" s:*:Bounce

list:
  stage: benchmark
  tags: [yuria]
  script:
    - *EXECUTORS
    - *PARAMS_RUN
    - rebench $PARAMS --experiment="CI ID $CI_PIPELINE_ID" --branch="$CI_COMMIT_REF_NAME" codespeed.conf all "${EXECUTORS[@]}" s:*:List

mandelbrot:
  stage: benchmark
  tags: [yuria2]
  script:
    - *EXECUTORS
    - *PARAMS_RUN
    - rebench $PARAMS --experiment="CI ID $CI_PIPELINE_ID" --branch="$CI_COMMIT_REF_NAME" codespeed.conf all "${EXECUTORS[@]}" s:*:Mandelbrot

nbody:
  stage: benchmark
  tags: [yuria3]
  script:
    - *EXECUTORS
    - *PARAMS_RUN
    - rebench $PARAMS --experiment="CI ID $CI_PIPELINE_ID" --branch="$CI_COMMIT_REF_NAME" codespeed.conf all "${EXECUTORS[@]}" s:*:NBody

permute:
  stage: benchmark
  tags: [yuria]
  script:
    - *EXECUTORS
    - *PARAMS_RUN
    - rebench $PARAMS --experiment="CI ID $CI_PIPELINE_ID" --branch="$CI_COMMIT_REF_NAME" codespeed.conf all "${EXECUTORS[@]}" s:*:Permute

queens:
  stage: benchmark
  tags: [yuria2]
  script:
    - *EXECUTORS
    - *PARAMS_RUN
    - rebench $PARAMS --experiment="CI ID $CI_PIPELINE_ID" --branch="$CI_COMMIT_REF_NAME" codespeed.conf all "${EXECUTORS[@]}" s:*:Queens

sieve:
  stage: benchmark
  tags: [yuria3]
  script:
    - *EXECUTORS
    - *PARAMS_RUN
    - rebench $PARAMS --experiment="CI ID $CI_PIPELINE_ID" --branch="$CI_COMMIT_REF_NAME" codespeed.conf all "${EXECUTORS[@]}" s:*:Sieve

storage:
  stage: benchmark
  tags: [yuria]
  script:
    - *EXECUTORS
    - *PARAMS_RUN
    - rebench $PARAMS --experiment="CI ID $CI_PIPELINE_ID" --branch="$CI_COMMIT_REF_NAME" codespeed.conf all "${EXECUTORS[@]}" s:*:Storage

towers:
  stage: benchmark
  tags: [yuria3]
  script:
    - *EXECUTORS
    - *PARAMS_RUN
    - rebench $PARAMS --experiment="CI ID $CI_PIPELINE_ID" --branch="$CI_COMMIT_REF_NAME" codespeed.conf all "${EXECUTORS[@]}" s:*:Towers

report-completion:
  stage: benchmark-completion
  tags: [yuria]
  script:
    - rebench --experiment="CI ID $CI_PIPELINE_ID" --report-completion codespeed.conf
