stages:
  - benchmark

variables:
  PYTHONUNBUFFERED: "true"
  GRAALVM_ARCHIVE: /home/gitlab-runner/.local/graalvm-0.12-linux-x86_64-dk.tar.gz
  RUBINIUS_BIN: /home/gitlab-runner/.local/rubinius/3.14/bin/rbx

before_script:
  - git submodule update --init --recursive

benchmark_job:
  stage: benchmark
  tags: [benchmarks, infinity]
  script:
    - ./benchmark.sh
